### ISSUE TITLE
검색창 검색 UI가 이상하게 표시됨

### ISSUE THREAD

**Issue by simnalamburt** [femiwiki/docker-mediawiki#131]
<img width="1003" alt="2018-05-17 1 58 05" src="https://user-images.githubusercontent.com/4435445/40157493-562ff9ee-59da-11e8-912b-c776a42540a3.png">

###### Reference
- https://femiwiki.com/index.php?title=%ED%8A%B9%EC%88%98%3A%EA%B2%80%EC%83%89&profile=default&fulltext=Search&search=asdfasdfasdf

**Comment by choidamdam** [comment]
https://github.com/femiwiki/femiwiki.com/blob/3cf400535cc7691bebdc7fd5904a2da9632a0cb4/www/skins/Femiwiki/resources/libraries/normalise.css

내부 input의 box-sizing 때문에 생기는 현상입니다. `box-sizing: border-box`가 적용되면 정상 출력됩니다.

```css
input[type="search"] {
	-webkit-appearance: textfield; /* 1 */
	-moz-box-sizing: content-box;
	-webkit-box-sizing: content-box; /* 2 */
	box-sizing: content-box;
}
```
