### ISSUE TITLE
모바일에서 검색 문서의 검색 결과 목록의 문단 줄바꿈 오류

### ISSUE THREAD

**Issue by paikwiki** [femiwiki/docker-mediawiki#160]
`.mw-search-results`의 자손 엘리먼트인 `.searchresult`의 스타일 정의를 `width: 38em;`에서 `max-width: 38em;`으로 수정해서 바로잡겠습니다.

````css
div.searchresult {
    font-size: 95%;
    width: 38em;
}
````

![batch_img_3027](https://user-images.githubusercontent.com/4120850/45286328-7ae1cf00-b520-11e8-8a4d-82df2ef144ea.jpg)
